# exp
exp_name: "CNO_double_cylinder_data_joint"
gpu: 0
seed: 0
results_path: "./results/"

# data
dataset_name: "double_cylinder_data" # fluidzero_data, double_cylinder_simulation_data, double_cylinder_measurement_data
dataset_path: "/path/to/gencp_dataset/"
num_workers: 12
normalizer: "range"
n_data_set: null  # 限制使用的数据量，null表示使用全部数据
length: 999 # 1000
dt: 10
sdf_threshold: 0.04

# choose
stage: "joint" # structure, fluid
model_name: "CNO" # SiT, UNet3d, CNO

use_torchcfm: True
use_diffusion: False 
use_surrogate: False

# model
is_resume: False
checkpoint_path: None
input_size: [128, 128] # [322, 226]
in_dim: 4
out_dim: 4
in_channels: 4
out_channels: 4
in_size: 128
# hidden_size: 128 # 768
# patch_size: [2, 2]
# num_heads: 4 # 12 
depth: 4 # 12 
# use_wavelet: False

# training
is_use_tb: True
x0_is_use_noise: True
test_interval: 1000
train_batch_size: 2
test_batch_size: 2

input_step: 3
output_step: 12
stride: 1
num_delta_t: 0 # 20

lr: 0.0003
sigma: 0.01

# iteration
train_mode: "iteration" # epoch, iteration
total_iterations: 100000
epochs: 1000

scheduler: "cosine"
# cosine
T_max: 100000
#step
step_size: 50
gamma: 0.5

# inference
num_sampling_steps: 10

# visualize
save_figs_path: "./visualization_results"
